### PR TITLE
Batch the request for book bag titles, to flesh them all at once.

### PR DESCRIPTION
**Pull request by stompro**
I've changed the bb_flesh.js script to request all titles in a bib bucket for fleshing at once.  I'm not all that familiar with javascript, so passing on the ordering of the titles puzzled me, I got it to work but I don't know if I did it the easiest way.

This change significantly improved the page load speed for us.

Signed-off-by: Josh Stompro <stomproj@larl.org>

### CODE REVIEW

**Comment by bmagic007** [comment]
Josh - what order are you trying to maintain? It looks like you are attempting to respect the container.biblio_record_entry_bucket_item.pos column which isn't populated by the bookbag_update.pl script. Do you have a custom method for filling up the container.biblio_record_entry_bucket_item rows?

**Comment by stompro** [comment]
Blake, sorry about not seeing this for a long long time.

I do use a different method to create the lists.  We add in the pos data based on the most recent active date of all the copies of a title.  That way the just added items are always first, or any that we just added additional copies to are first.

We also do separate lists for on order titles vs  newly arrived, and we sort those by when the on order copies are created.
Here is the sql we use.
https://gist.github.com/stompro/9c01e4b3ebc6d8765a2aa19c4d4e1ef1

**Comment by bmagic007** [comment]
Josh - Are you still using some version of this perl script? Evergreen has carousels built-in now. I've pretty much stopped working on this code. (your merge request is from 2018)

**Comment by bmagic007** [comment]
Josh - or rather, a version of the OPAC pieces? Does this implementation of the carousels solve a problem that the built-in version doesn't?

**Comment by stompro** [comment]
Blake, I'm prepping for an upgrade to 3.10, and was just going through previous changes and make sure I have things backed up and documented.  So we still currently use this, but will try and switch to the built in Carousel when we upgrade.  I just felt bad about leaving your question hanging for so long.

**Comment by bmagic007** [comment]
I went ahead and merged it. Thanks for contributing back. Hopefully others will find it useful. Incidentally, we still use this carousel method but we have a future project to migrate to the built-in method. There are dozens of carousels that need to manually migrated.

**Pull request merged**
